### ISSUE TITLE
upload error

### ISSUE THREAD

**Issue by emilysusann** [generalludd/expenses#10]
i tried to upload a .qfx file associated with the associated bank account into our expenses app and it said this:

![image](https://user-images.githubusercontent.com/67062568/102152569-ebcc6b80-3e3a-11eb-9778-7a3afe403c5e.png)

**Comment by emilysusann** [comment]
I tried ofx too just to see if it would work and i got an error on that too
![image](https://user-images.githubusercontent.com/67062568/102152712-36e67e80-3e3b-11eb-904f-393c71a0a5ce.png)

**Comment by generalludd** [comment]
@emilysusann The library that manages this needed to be updated. It now appears to be working. Could you check this out again?

**Comment by emilysusann** [comment]
Looks like its working! wahoo!
![image](https://user-images.githubusercontent.com/67062568/102161275-a9ac2580-3e4c-11eb-835d-bf76e9ceb3e0.png)
