### ISSUE TITLE
Select account - can we add "uncategorized" as selectable field?

### ISSUE THREAD

**Issue by emilysusann** [generalludd/expenses#15]
If i click "select all" it chooses only transactions where the account has been defined.

I'd like to also view transactions that haven't been defined an account (ie. the account field is blank)

![image](https://user-images.githubusercontent.com/67062568/103465583-d09aa080-4d02-11eb-8bb9-c340fc8ee49c.png)

**Comment by generalludd** [comment]
I have fixed this. It will be released to live shortly.
